name: CI - integration test output-affected-projects

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: ./.github/workflows/nx-cloud-main.yml
    with:
      working-directory: ./integration-tests/npm
      parallel-commands-on-agents: |
        npx nx run react-app:build
      output-affected-projects : true

  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    with:
      working-directory: ./integration-tests/npm
      number-of-agents: 1

  check-affectedProjects-output:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: If successfully outputed affected projects
        if: ${{contains(needs.main.outputs.affectedProjects, 'react-app')}} && ${{contains(needs.main.outputs.affectedProjects, 'react-app-e2e')}}
        run: node -e console.log('Affected apps were outputed successfully)
      - name: If NOT successfully outputed affected projects
        if: ${{!contains(needs.main.outputs.affectedProjects, 'react-app')}} || ${{!contains(needs.main.outputs.affectedProjects, 'react-app-e2e')}}
        run: node -e throw new Error('Affected apps were NOT outputed successfully)
